# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 059d8eaadd29c5317ad75141f89953291921bd5d73380f3b01e6634d2dc024a8a132eb8ad29427a4a849d707ae9fd54618bde841f9c11e917d366b1124945c3f

test:
  secret_key_base: 5eb71ea5703e8d92d9f63a7dedaeabac2647f65286a2cf8091328a4ebb8068f3817fde03c8e06f76d043805698e32807131ee949cba027f4882529228143dab2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
